### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by chdanielmueller** [devlouisc/swagger-express#1]
Hey,

I saw your fork from swagger-express and it seems like you are doing what I wanted to do.
- Swagger 2.0 spec implementing
- Only JSDoc support needed

There are some things which I would like to add:
- Get the model information from a mongoose spec
- Add swagger-ui as dependency (https://github.com/juliusza/swagger-express)

If there is anything I could help you with give me a shout.

Daniel

**Comment by hilouisc** [comment]
Hi,

Thanks for the offer.

I'm working on getting a working release out right now. I'll create issues for features to add when I'm ready. Keep an eye out.

// Louis
