### ISSUE TITLE
Swagger object validation

### ISSUE THREAD

**Issue by hilouisc** [devlouisc/swagger-express#2]
Right now, the Swagger object is constructed from the JSDoc comments so there is no validation to make sure that it conforms to the Swagger 2.0 specs. We need to take the constructed Swagger object and run it through some kind of validation that throws an exception if the object is invalid to notify the user that something is wrong.

**Comment by chdanielmueller** [comment]
I'm working on it

**Comment by chdanielmueller** [comment]
Do you have time to take a look at my pull request?

**Comment by hilouisc** [comment]
I've skimmed them briefly yesterday, but I'll take a look at them in detail it tomorrow.

**Comment by hilouisc** [comment]
I've merged your pull request. See comments. This issue still unresolved and is up for grabs.

**Comment by chdanielmueller** [comment]
I implemented swagger-tools
You did merge just a little bit of my changes
Please take a look at them and implement it if you like it.
I will not write my code 2 times.

**Comment by Castyr** [comment]
Added validation via swagger-tools.
