### ISSUE TITLE
Shorthand path

### ISSUE THREAD

**Issue by mohsen1** [devlouisc/swagger-express#6]
``` js
/**
 *  @swagger
 *  /: get: responses: 200:
 *    description: hello world
 *    summary: hello
 */
app.get('/', function (req, res) {
    res.send('Hello World!');
});
```

A shorthand syntax like that is going to be handy. parsing the path won't be too hard, you just need to to rely on "colon-space"  `:` (really `/s+\:/`) as a separator.

**Comment by hilouisc** [comment]
I'm using js-yaml to parse the comment string and it's white-space sensitive. You could create a module that takes your proposed YAML shorthand syntax and returns valid YAML. Then I'd be able to put that module between reading the comment and parsing it with js-yaml.

**Comment by mohsen1** [comment]
I don't have the time to make that library. If I did something with jsdoc and Swagger I might spend some time writing it.
